#ifndef STEPPER_CONFIG_H
#define STEPPER_CONFIG_H

#define STEPPER_X_PULSE_PORT DT_NODELABEL(gpioa)
#define STEPPER_X_PULSE_PIN 0
#define STEPPER_X_DIR_PORT DT_NODELABEL(gpioa)
#define STEPPER_X_DIR_PIN 1
#define STEPPER_X_ENABLE_PORT DT_NODELABEL(gpioa)
#define STEPPER_X_ENABLE_PIN 4

#define STEPPER_Y_PULSE_PORT DT_NODELABEL(gpiob)
#define STEPPER_Y_PULSE_PIN 0
#define STEPPER_Y_DIR_PORT DT_NODELABEL(gpiob)
#define STEPPER_Y_DIR_PIN 1
#define STEPPER_Y_ENABLE_PORT DT_NODELABEL(gpiob)
#define STEPPER_Y_ENABLE_PIN 2

#define STEPPER_Z_PULSE_PORT DT_NODELABEL(gpioc)
#define STEPPER_Z_PULSE_PIN 0
#define STEPPER_Z_DIR_PORT DT_NODELABEL(gpioc)
#define STEPPER_Z_DIR_PIN 1
#define STEPPER_Z_ENABLE_PORT DT_NODELABEL(gpioc)
#define STEPPER_Z_ENABLE_PIN 2

#define STEPPER_GRIPPER_PULSE_PORT DT_NODELABEL(gpioc)
#define STEPPER_GRIPPER_PULSE_PIN 3
#define STEPPER_GRIPPER_DIR_PORT DT_NODELABEL(gpioc)
#define STEPPER_GRIPPER_DIR_PIN 4
#define STEPPER_GRIPPER_ENABLE_PORT DT_NODELABEL(gpioc)
#define STEPPER_GRIPPER_ENABLE_PIN 5

#define STEPPER_DEFAULT_SPEED_US 1000
#define STEPPER_FAST_SPEED_US 500
#define STEPPER_SLOW_SPEED_US 2000

#endif
