#ifndef STEPPER_CONFIG_H
#define STEPPER_CONFIG_H

// X-Axis Stepper
#define STEPPER_X_PULSE_PORT DT_NODELABEL(gpiod)
#define STEPPER_X_PULSE_PIN 15
#define STEPPER_X_DIR_PORT DT_NODELABEL(gpiof)
#define STEPPER_X_DIR_PIN 14
#define STEPPER_X_ENABLE_PORT DT_NODELABEL(gpioe)
#define STEPPER_X_ENABLE_PIN 9

// Y-Axis Stepper (Left rail)
#define STEPPER_Y1_PULSE_PORT DT_NODELABEL(gpiof)
#define STEPPER_Y1_PULSE_PIN 5
#define STEPPER_Y1_DIR_PORT DT_NODELABEL(gpiof)
#define STEPPER_Y1_DIR_PIN 4
#define STEPPER_Y1_ENABLE_PORT DT_NODELABEL(gpioe)
#define STEPPER_Y1_ENABLE_PIN 8

// Y-Axis Stepper 2 (Right rail)
#define STEPPER_Y2_PULSE_PORT DT_NODELABEL(gpiof)
#define STEPPER_Y2_PULSE_PIN 10
#define STEPPER_Y2_DIR_PORT DT_NODELABEL(gpioe)
#define STEPPER_Y2_DIR_PIN 7
#define STEPPER_Y2_ENABLE_PORT DT_NODELABEL(gpiod)
#define STEPPER_Y2_ENABLE_PIN 14

// Z-Axis Stepper
#define STEPPER_Z_PULSE_PORT DT_NODELABEL(gpiod)
#define STEPPER_Z_PULSE_PIN 5
#define STEPPER_Z_DIR_PORT DT_NODELABEL(gpiod)
#define STEPPER_Z_DIR_PIN 6
#define STEPPER_Z_ENABLE_PORT DT_NODELABEL(gpiod)
#define STEPPER_Z_ENABLE_PIN 7

#define STEPPER_GRIPPER_PULSE_PORT DT_NODELABEL(gpioc)
#define STEPPER_GRIPPER_PULSE_PIN 6
#define STEPPER_GRIPPER_DIR_PORT DT_NODELABEL(gpioc)
#define STEPPER_GRIPPER_DIR_PIN 7
#define STEPPER_GRIPPER_ENABLE_PORT DT_NODELABEL(gpioc)
#define STEPPER_GRIPPER_ENABLE_PIN 8

#define STEPPER_DEFAULT_SPEED_US 1000
#define STEPPER_FAST_SPEED_US 500
#define STEPPER_SLOW_SPEED_US 2000

#endif
